name: Sync to Gitee
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  workflow_run:
    workflows: ["Get bing wallpaper Every Day."]
    types: [completed]

jobs:
  sync-to-gitee:
    name: Sync to Gitee
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:hanhuang22/mybingwallpaper.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:Hyman25/mybingwallpaper.git 
